### ISSUE TITLE
Add max-version in brackets-registry

### ISSUE THREAD

**Issue by fdecampredon** [tomsdev/brackets-typescript-code-intel#16]
Could you please do something about this extension ?
It's not working with current brackets version, it's based on an outdated typescript version, and worse it prevent other typescript related extensions to work properly.
I had a lot of users of my own extension reporting bugs before realizing that they had both mine and this extension installed and that it was the source of the problem.
Could you please add a *max* compatible version in brackets or remove it from the registry ? :-)

**Comment by tomsdev** [comment]
Sorry about the delay, GitHub didn't send me an email for this issue. I didn't find a way to specify a "max" compatible version so I just locked it to Brackets version 0.23.
